spring: 
  profiles: 
    active: dev
    
---

server:
  port: 8001
  

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.yang.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: dev
  application:
    name: microservicecloud-dept-yj01
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源
    driver-class-name: org.gjt.mm.mysql.Driver     #数据库驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

#入住eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: yang-microservicecloud
  company.name: www.yang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---

server:
  port: 8001
  

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.yang.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  profiles: test
  application:
    name: microservicecloud-dept-yj01
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源
    driver-class-name: org.gjt.mm.mysql.Driver     #数据库驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

#入住eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: yang-microservicecloud
  company.name: www.yang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
